const newNoteButton = document.querySelector('#newnote');
const deleteButton = document.querySelector('#del');
const saveButton = document.querySelector('#save');
const toolbar = document.querySelector('#tools');
const docTools = document.querySelectorAll('#tools .doc-tool');
const contentArea = document.querySelector('#note article');
const today = document.querySelector('#note time');
const sideBar = document.querySelector('#sidebar ul');
const listButton = document.querySelector('#list');
const hamburger = document.querySelector('#hamburger');
const close = document.querySelector('#close');
const tableTemplate = document.querySelector('#tableTemplate');
const addRow = document.querySelector('#addRow');
const addColumn = document.querySelector('#addColumn');
const boldButton = document.querySelector('#bold');
const italicsButton = document.querySelector('#italics');
const underlineButton = document.querySelector('#underline');
const firstNoteButton = document.querySelector('.landing-page-text .new-note')
const toolLabels = document.querySelectorAll('.tool-label');
